Gregs-MacBook-Air:StopGoContinue Greg$ node client.js
@founderscoders per-greg test  #stop
{ created_at: 'Tue Feb 24 16:43:49 +0000 2015',
  id: 570262833931296800,
  id_str: '570262833931296768',
  text: '@founderscoders per-greg test  #stop',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 971846516,
  in_reply_to_user_id_str: '971846516',
  in_reply_to_screen_name: 'founderscoders',
  user:
   { id: 1613170598,
     id_str: '1613170598',
     name: 'Greg Aubert',
     screen_name: 'gregaubs',
     location: 'London',
     url: 'http://gregaubert.com/',
     description: 'New Entrepreneurs Foundation 2014   |   Travel, tourism & startups',
     protected: false,
     verified: false,
     followers_count: 80,
     friends_count: 65,
     listed_count: 9,
     favourites_count: 1,
     statuses_count: 87,
     created_at: 'Mon Jul 22 16:21:53 +0000 2013',
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     lang: 'en-gb',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: '676B67',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000032343247/a7cbb5fd198fc0794589b73c75e91251.jpeg',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000032343247/a7cbb5fd198fc0794589b73c75e91251.jpeg',
     profile_background_tile: false,
     profile_link_color: '6595A3',
     profile_sidebar_border_color: 'FFFFFF',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/378800000171420897/763c79ed2ed13af097ca4e7bf382430e_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000171420897/763c79ed2ed13af097ca4e7bf382430e_normal.jpeg',
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [ [Object] ],
     trends: [],
     urls: [],
     user_mentions: [ [Object] ],
     symbols: [] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1424796229237' }
RT @RorySedgwick: @founderscoders testing #STOP
{ created_at: 'Tue Feb 24 16:44:42 +0000 2015',
  id: 570263055537455100,
  id_str: '570263055537455104',
  text: 'RT @RorySedgwick: @founderscoders testing #STOP',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
   { id: 2379098512,
     id_str: '2379098512',
     name: 'Disco Fingers',
     screen_name: 'discofingers',
     location: 'Oslo',
     url: 'http://www.discofingers.com',
     description: 'Our goal is to turn you into a music composer.',
     protected: false,
     verified: false,
     followers_count: 150,
     friends_count: 451,
     listed_count: 3,
     favourites_count: 293,
     statuses_count: 274,
     created_at: 'Mon Mar 03 12:19:44 +0000 2014',
     utc_offset: 3600,
     time_zone: 'Ljubljana',
     geo_enabled: false,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: '000000',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_link_color: '45ADA8',
     profile_sidebar_border_color: '000000',
     profile_sidebar_fill_color: '000000',
     profile_text_color: '000000',
     profile_use_background_image: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/534688128250830848/JX58_qve_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/534688128250830848/JX58_qve_normal.jpeg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/2379098512/1407940702',
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status:
   { created_at: 'Tue Feb 24 12:19:48 +0000 2015',
     id: 570196391567466500,
     id_str: '570196391567466496',
     text: '@founderscoders testing #STOP',
     source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
     truncated: false,
     in_reply_to_status_id: null,
     in_reply_to_status_id_str: null,
     in_reply_to_user_id: 971846516,
     in_reply_to_user_id_str: '971846516',
     in_reply_to_screen_name: 'founderscoders',
     user:
      { id: 2447724711,
        id_str: '2447724711',
        name: 'Rory Sedgwick',
        screen_name: 'RorySedgwick',
        location: 'London',
        url: null,
        description: null,
        protected: false,
        verified: false,
        followers_count: 15,
        friends_count: 66,
        listed_count: 1,
        favourites_count: 1,
        statuses_count: 21,
        created_at: 'Sun Mar 30 18:23:45 +0000 2014',
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_link_color: '4A913C',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/511502370375618560/bVwVBWH2_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/511502370375618560/bVwVBWH2_normal.jpeg',
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null },
     geo: null,
     coordinates: null,
     place: null,
     contributors: null,
     counretweet_t: 2,
     favorite_count: 0,
     entities:
      { hashtags: [Object],
        trends: [],
        urls: [],
        user_mentions: [Object],
        symbols: [] },
     favorited: false,
     retweeted: false,
     possibly_sensitive: false,
     filter_level: 'low',
     lang: 'en' },
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [ [Object] ],
     trends: [],
     urls: [],
     user_mentions: [ [Object], [Object] ],
     symbols: [] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1424796282072' }